In [5]:
l = [23245,27,546,215,-1234]

In [6]:
l

[23245, 27, 546, 215, -1234]

In [7]:
import numpy as np

In [8]:
np

<module 'numpy' from '/Users/lauranne/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'>

In [9]:
a=np.array(l)

In [10]:
a

array([23245,    27,   546,   215, -1234])

In [8]:
b=np.array([12,455,63.3,True,"abc"])

In [9]:
b

array(['12', '455', '63.3', 'True', 'abc'],
      dtype='<U32')

In [10]:
#In Arrays Everything has to be the same datatype

In [11]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [12]:
l.pop()

-1234

In [13]:
l

[23245, 27, 546, 215]

In [15]:
 a.mean() #Arrays allow to use many varieties of functions in a list, applied to a whole list it becomes ver useful

4559.8000000000002

In [16]:
a

array([23245,    27,   546,   215, -1234])

In [17]:
a[1]

27

In [18]:
a[::2]

array([23245,   546, -1234])

In [19]:
a[::-2]

array([-1234,   546, 23245])

---

In [31]:
#Slicing Arrays

In [21]:
a[2:]

array([  546,   215, -1234])

In [22]:
a[1:5]

array([   27,   546,   215, -1234])

In [23]:
a[::-3]

array([-1234,    27])

In [25]:
#When creating a slice of an array, 
   ##you are not creating a new array, 
   ##you are creating a VIEW of the same array
#If you overwrite the view of that array with new values, the original array will be equally impacted

In [26]:
b= a[::-3]

In [27]:
b

array([-1234,    27])

In [28]:
b[1]=2972313

In [29]:
b

array([  -1234, 2972313])

In [30]:
a

array([  23245, 2972313,     546,     215,   -1234])

In [40]:
c=a.copy()  #Create a copy of an array to not overwrite an existing array that you do not want to alterate

In [36]:
c

array([  23245, 2972313,     546,     215,   -1234])

In [37]:
c[0]=9

In [38]:
c

array([      9, 2972313,     546,     215,   -1234])

In [39]:
a

array([  23245, 2972313,     546,     215,   -1234])